### ISSUE TITLE
use of pywt name on PyPI

### ISSUE THREAD

**Issue by rgommers** [Knapstad/pywt#1]
Hi @Knapstad, I'm one of the maintainers of PyWavelets. As you may perhaps know, PyWavelets uses `pywt` as its import name - this sometimes confuses users and they do `pip install pywt` rather than `pip install pywavelets` (recent example [here](https://groups.google.com/forum/#!topic/pywavelets/Ris-NVVLI9w)). That will give them this package, which is not so helpful.

Since PyWavelets is quite widely used and this package seems dormant, I am hoping you will consider giving us the `pywt` name on PyPI, so we can fix the issue for our users. Would you be willing to do that?

**Comment by Knapstad** [comment]
Sure no problem.

Is there a process to give i over to you?

**Comment by rgommers** [comment]
Awesome, thank you. You can just add me as an admin to https://pypi.org/project/pywt, and then I can take it from there.

**Comment by Knapstad** [comment]
@rgommers whats your pypi username?

**Comment by Knapstad** [comment]
@rgommers nevermind i found it :)

**Comment by rgommers** [comment]
thanks again @Knapstad 

done:
```
$ pip install pywt --no-cache
ERROR: Could not find a version that satisfies the requirement pywt (from versions: none)
ERROR: No matching distribution found for pywt
```

@grlee77 added you as owner as well

**Comment by Knapstad** [comment]
@rgommers happy to help.

**Comment by grlee77** [comment]
Thank you both for addressing this.
